apiVersion: apps/v1
kind: Deployment
metadata:
  name: myazureaks
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myazureaks
  template:
    metadata:
      labels:
        app: myazureaks
    spec:
      containers:
        - name: myazureaks
          image: sarvesh2301/docker2218-app:latest
          ports:
            - containerPort: 80
