apiVersion: apps/v1
kind: Deployment
metadata:
  name: myazureaks
  namespace: sarvesh
  labels:
   app: myazureaks
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myazureaks
  template:
    metadata:
      labels:
        app: myazureaks
    spec:
      containers:
        - name: myazureaks
          image: sarveshcontainer.azurecr.io/docker2218-app:latest
          ports:
            - containerPort: 5000
      imagePullSecrets:
      - name: ram
      
